# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MigDiff < Formula
  desc "Show Django migration diffs between git branches"
  homepage "https://github.com/kumitaakira453/mig-diff"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumitaakira453/mig-diff/releases/download/v0.1.0/mig-diff_0.1.0_darwin_amd64.tar.gz"
      sha256 "c529b87551db1438e3374581722d811bea6d1d18613de1deb727d999796188b1"

      define_method(:install) do
        bin.install "mig-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumitaakira453/mig-diff/releases/download/v0.1.0/mig-diff_0.1.0_darwin_arm64.tar.gz"
      sha256 "1a075c3c8d7305de1d3fff7d42241ec231267e98ec0a64b336e4a1e7b3167444"

      define_method(:install) do
        bin.install "mig-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumitaakira453/mig-diff/releases/download/v0.1.0/mig-diff_0.1.0_linux_amd64.tar.gz"
      sha256 "e1342e9048a7eb6e75df08911ead728b8d1550f1881c0b258f754911e4540219"
      define_method(:install) do
        bin.install "mig-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumitaakira453/mig-diff/releases/download/v0.1.0/mig-diff_0.1.0_linux_arm64.tar.gz"
      sha256 "1355f9767b27cb13215618db8807719fa5d1032712b940ecb56519d208312220"
      define_method(:install) do
        bin.install "mig-diff"
      end
    end
  end
end
