# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MigDiff < Formula
  desc "Show Django migration diffs between git branches"
  homepage "https://github.com/kumitaakira453/mig-diff"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kumitaakira453/mig-diff/releases/download/v0.1.1/mig-diff_0.1.1_darwin_amd64.tar.gz"
      sha256 "f5337557d05424fac1ff659647b6caf7de812fa712d13452fdf77ca571b23054"

      define_method(:install) do
        bin.install "mig-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kumitaakira453/mig-diff/releases/download/v0.1.1/mig-diff_0.1.1_darwin_arm64.tar.gz"
      sha256 "cca495e77e743a8f7af07dfd0643f52e72c880288d58da868c6fc161059b4646"

      define_method(:install) do
        bin.install "mig-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumitaakira453/mig-diff/releases/download/v0.1.1/mig-diff_0.1.1_linux_amd64.tar.gz"
      sha256 "a9e7e8b8511976f79d63d415d35bcd4b23fac229fa244f0b8c479e03dc6fcb09"
      define_method(:install) do
        bin.install "mig-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kumitaakira453/mig-diff/releases/download/v0.1.1/mig-diff_0.1.1_linux_arm64.tar.gz"
      sha256 "fd942a25d3ad69d4dd5c5119116ae4e2579e0ddeb0c6c36ea14c97d99dcbe671"
      define_method(:install) do
        bin.install "mig-diff"
      end
    end
  end
end
